set nocompatible

if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

" ================ General Config ====================

" execute pathogen#infect()
set number relativenumber       "Line numbers are good
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set belloff=all
" set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim

" ================ Other Personal Config ====================
set colorcolumn=115
set mouse=a
" set shiftround
set splitbelow
set splitright
set title
set laststatus=2
set nowrap
" set wrap

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

"turn on syntax highlighting
syntax on

" Change leader to a comma because the backslash is too far away
" That means all \x commands turn into ,x
" The mapleader has to be set before vundle starts loading all
" the plugins.
let mapleader=" "
set timeout timeoutlen=1500

" ================ Turn Off Swap Files ==============

set noswapfile
set nobackup
set nowb

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo') && !isdirectory(expand('~').'/.vim/backups')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" ================ Folds ============================

set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

" ================ Scrolling ========================

set scrolloff=5         "Start scrolling when we're 5 lines away from margins
set sidescrolloff=15
set sidescroll=1

" ================ Search ===========================

set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

" ================ Indentation ======================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

filetype plugin on
filetype indent on

" Display tabs and trailing spaces visually
set list listchars=tab:»»,trail:·

" set linebreak    "Wrap lines at convenient points


" ================ Custom Settings ========================

nnoremap <leader>ev <esc>:vsplit $MYVIMRC<cr>
nnoremap <leader>rv <esc>:source $MYVIMRC<cr>

nnoremap <silent>cc <esc>:set cursorline! cursorcolumn!<cr>

" temporary
source ~/.dotfiles/symlinks/vimrc.old

" set path+=**
set wildmenu
set encoding=utf-8
" set noswapfile
scriptencoding utf-8
